<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Produce a function which can get or set global options — setGlobalOptions • GlobalOptions</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script>

<!-- bootstrap-toc -->
<link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>




<meta property="og:title" content="Produce a function which can get or set global options — setGlobalOptions" />
<meta property="og:description" content="Produce a function which can get or set global options" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body data-spy="scroll" data-target="#toc">
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">GlobalOptions</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/GlobalOptions.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jokergoo/GlobalOptions/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Produce a function which can get or set global options</h1>
    
    <div class="hidden name"><code>setGlobalOptions.rd</code></div>
    </div>

    <div class="ref-description">
    <p>Produce a function which can get or set global options</p>
    </div>

    <pre class="usage"><span class='fu'>setGlobalOptions</span><span class='op'>(</span><span class='va'>...</span><span class='op'>)</span></pre>

    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>...</th>
      <td><p>specification of options, see 'details' section</p></td>
    </tr>
    </table>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The function has a short name <code><a href='set_opt.html'>set_opt</a></code>.</p>
<p>The most simple way is to construct an option function (e.g. <code>opt()</code>) as:</p>
<p></p><pre>
    <span class='va'>opt</span> <span class='op'>=</span> <span class='fu'><a href='set_opt.html'>set_opt</a></span><span class='op'>(</span>
        <span class='st'>"a"</span> <span class='op'>=</span> <span class='fl'>1</span>,
        <span class='st'>"b"</span> <span class='op'>=</span> <span class='st'>"text"</span>
    <span class='op'>)</span>  </pre>

<p>Then users can get or set the options by</p>
<p></p><pre>
    <span class='fu'>opt</span><span class='op'>(</span><span class='op'>)</span>
    <span class='fu'>opt</span><span class='op'>(</span><span class='st'>"a"</span><span class='op'>)</span>
    <span class='va'>opt</span><span class='op'>$</span><span class='va'>a</span>
    <span class='va'>opt</span><span class='op'>[[</span><span class='st'>"a"</span><span class='op'>]</span><span class='op'>]</span>
    <span class='fu'>opt</span><span class='op'>(</span><span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='st'>"a"</span>, <span class='st'>"b"</span><span class='op'>)</span><span class='op'>)</span>
    <span class='fu'>opt</span><span class='op'>(</span><span class='st'>"a"</span>, <span class='st'>"b"</span><span class='op'>)</span>
    <span class='fu'>opt</span><span class='op'>(</span><span class='st'>"a"</span> <span class='op'>=</span> <span class='fl'>2</span><span class='op'>)</span>
    <span class='va'>opt</span><span class='op'>$</span><span class='va'>a</span> <span class='op'>=</span> <span class='fl'>2</span>
    <span class='va'>opt</span><span class='op'>[[</span><span class='st'>"a"</span><span class='op'>]</span><span class='op'>]</span> <span class='op'>=</span> <span class='fl'>2</span>
    <span class='fu'>opt</span><span class='op'>(</span><span class='st'>"a"</span> <span class='op'>=</span> <span class='fl'>2</span>, <span class='st'>"b"</span> <span class='op'>=</span> <span class='st'>"new_text"</span><span class='op'>)</span>  </pre>

<p>Options can be reset to their default values by:</p>
<p></p><pre>
    <span class='fu'>opt</span><span class='op'>(</span>RESET <span class='op'>=</span> <span class='cn'>TRUE</span><span class='op'>)</span>  </pre>

<p>The value for each option can be set as a list which contains more configurations of the option:</p>
<p></p><pre>
    <span class='va'>opt</span> <span class='op'>=</span> <span class='fu'><a href='set_opt.html'>set_opt</a></span><span class='op'>(</span>
        <span class='st'>"a"</span> <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/list.html'>list</a></span><span class='op'>(</span>.value <span class='op'>=</span> <span class='fl'>1</span>,
                   .length <span class='op'>=</span> <span class='fl'>1</span>,
                   .class <span class='op'>=</span> <span class='st'>"numeric"</span>,
                   .validate <span class='op'>=</span> <span class='kw'>function</span><span class='op'>(</span><span class='va'>x</span><span class='op'>)</span> <span class='va'>x</span> <span class='op'>&gt;</span> <span class='fl'>0</span><span class='op'>)</span>
    <span class='op'>)</span>  </pre>

<p>The different fields in the list can be used to filter or validate the option values.</p>
<dl>
  <dt><code>.value</code></dt><dd><p>The default value.</p></dd>
  <dt><code>.length</code></dt><dd><p>The valid length of the option value. It can be a vector, the check will be passed if one of the length fits.</p></dd>
  <dt><code>.class</code></dt><dd><p>The valid class of the option value. It can be a vector, the check will be passed if one of the classes fits.</p></dd>
  <dt><code>.validate</code></dt><dd><p>Validation function. The input parameter is the option value and should return a single logical value.</p></dd>
  <dt><code>.failed_msg</code></dt><dd><p>Once validation failed, the error message that is printed.</p></dd>
  <dt><code>.filter</code></dt><dd><p>Filtering function. The input parameter is the option value and it should return a filtered option value.</p></dd>
  <dt><code>.read.only</code></dt><dd><p>Logical. The option value can not be modified if it is set to <code>TRUE</code>.</p></dd>
  <dt><code>.visible</code></dt><dd><p>Logical. Whether the option is visible to users.</p></dd>
  <dt><code>.private</code></dt><dd><p>Logical. The option value can only be modified in the same namespace where the option function is created.</p></dd>
  <dt><code>.synonymous</code></dt><dd><p>a single option name which should have been already defined ahead of current option. The option specified will be shared by current option.</p></dd>
  <dt><code>.description</code></dt><dd><p>a short text for describing the option. The description is only used when printing the object.</p></dd>

</dl>

<p>For more detailed explanation, please go to the vignette.</p>
    <h2 class="hasAnchor" id="author"><a class="anchor" href="#author"></a>Author</h2>

    <p>Zuguang Gu &lt;z.gu@dkfz.de&gt;</p>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='va'>opt</span> <span class='op'>=</span> <span class='fu'><a href='set_opt.html'>set_opt</a></span><span class='op'>(</span>
    a <span class='op'>=</span> <span class='fl'>1</span>,
    b <span class='op'>=</span> <span class='st'>"text"</span>
<span class='op'>)</span>
<span class='va'>opt</span>
</div><div class='output co'>#&gt;  Option Value
#&gt;  ------:-------
#&gt;  a      1    
#&gt;  b      text </div><div class='input'><span class='co'># for more examples, please go to the vignette</span>
</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <nav id="toc" data-toggle="toc" class="sticky-top">
      <h2 data-toc-skip>Contents</h2>
    </nav>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Zuguang Gu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


